# Header
menu:
  home: /
  categories: /categories
  archives: /archives
  tags: /tags
  about: /about
rss: /atom.xml

# Place your favicon.ico to /source directory.
favicon: /favicon.ico

avatar: /avatar.jpg
author: hiluluke

# Set default keywords (Use a comma to separate)
keywords: "hiluluke note 笔记 前端 技术 希鲁鲁克 javascript "

description: "我是一个粉刷匠"

