# Header
menu:
  home: /
  categories: /categories
  archives: /archives
  tags: /tags
  about: /about
rss: /atom.xml

# Place your favicon.ico to /source directory.
favicon: /favicon.ico
avatar: /avatar.jpeg
author: hiluluke

# Set default keywords (Use a comma to separate)
keywords: "hiluluke note 笔记 前端 技术 希鲁鲁克 javascript "

#  set social
#  you can set github twitter weibo v2ex douban zhihu codepen facebook
social:
  github: https://github.com/wszgxa
  v2ex: http://v2ex.com/member/hiluluke
  zhihu: https://www.zhihu.com/people/zhao-guo-xu
  twitter: https://twitter.com/Hiluluke
  codepen: http://codepen.io/hiluluke

duoshuo_shortname: hiluluke
# disqus_shortname: hilus-note