# Header
menu:
  home: /
  categories: /categories
  # archives: /archives
  tags: /tags
  about: /about
  rss: /atom.xml

# Place your favicon.ico to /source directory.
favicon: /favicon.ico
avatar: /images/avatar.jpg
author: ousui

# Set default keywords (Use a comma to separate)
keywords: "ousui note"

#  set social
#  you can set github twitter weibo v2ex douban zhihu codepen facebook
social:
  github: https://github.com/ousui
  v2ex: http://v2ex.com/member/ppwangs
  zhihu: https://www.zhihu.com/people/ousui
#  twitter: https://twitter.com/Hiluluke
#  codepen: http://codepen.io/hiluluke

duoshuo_shortname: ousui
# disqus_shortname: hilus-note

# baidu_analytics: 

# tencent_analytics: 
# google_analytics: UA-83014983-1
